# -*- coding: utf-8 -*-
"""task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBvDepiqamxbcgRYaL2roTubz-T2EWMp
"""

print("my name is yara")

